MVCContactListv2/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCContactListv2.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}

MVCContactListv2/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCContactListv2.Models;
using MVCContactListv2.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVCContactListv2.Controllers
{
    public class PeopleController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["Title"] = "Index";
            var list = DataManager.ListPeople();
            return View(list);
        }

        

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Title"] = "Create Contact";

            return View();
        }

        [HttpPost]
        public IActionResult Create(PeopleCreateVM peopleCreateVM)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Title"] = "Create Contact";
                return View(peopleCreateVM);
            }

            DataManager.AddPerson(peopleCreateVM);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Edit Contact";
            var contact = DataManager.GetContactById(id);
            return View(contact);
        }

        [HttpPost]
        public IActionResult Edit(int id, PeopleEditVM newPeopleEditVM)
        {
            // Todo: kanske behöver ändras för VM
            if (!ModelState.IsValid)
            {
                ViewData["Title"] = "Edit Contact";
                return View(newPeopleEditVM);
            }

            DataManager.EditContact(id, newPeopleEditVM);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int id) {
            DataManager.RemoveContactById(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

MVCContactListv2/Views/People/Create.cshtml
@model PeopleCreateVM

<div class="form-group">
    <form asp-controller="People" asp-action="Create">
        <label asp-for="Name"></label>
        <br />
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="validationSpan"></span>
        <br />

        <label asp-for="Email"></label>
        <br />
        <input asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="validationSpan"></span>
        <br />

        <label asp-for="BotCheck"></label>
        <br />
        <input asp-for="BotCheck" type="text" class="form-control"/>
        <span asp-validation-for="BotCheck" class="validationSpan"></span>


        <br />
        <br />
        <input type="submit" value="Submit" class="btn btn-default"/>

    </form>

</div>

MVCContactListv2/Views/People/Edit.cshtml
@model PeopleEditVM

<div class="form-group">
    <form asp-controller="People" asp-action="Edit">
        <label asp-for="Name"></label>
        <br />
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
        <br />

        <label asp-for="Email"></label>
        <br />
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email"></span>
        <br />
        <br />

        <input type="submit" value="Submit" class="btn btn-default" />

    </form>

    <br />

    <form asp-controller="People" asp-action="Remove" asp-route-id="@Model.ID">
        <input type="submit" value="Remove Contact" class="btn btn-danger" />
    </form>



</div>

MVCContactListv2/Views/People/Index.cshtml
<h3>Click contact to edit:</h3>

@Html.Partial("_TestOfPartialLayout")

<ul class="list-group">
    @foreach (var item in Model)
    {
        <li class="list-group-item">
            @if (item.ShowAsHighlighted)
                {
                <a style="color: mediumseagreen;" asp-controller="People" asp-action="Edit" asp-route-id="@item.Id">@($"{item.Name} - {item.Email}")</a>
                    <span style="float: right; color: darkslategrey;">ACME-VIP</span>

            }
            else
            {
                <a asp-controller="People" asp-action="Edit" asp-route-id="@item.Id">@($"{item.Name} - {item.Email}")</a>
            }

        </li>

    }
</ul>
@Html.Partial("_TestOfPartialLayout")